### ISSUE TITLE
Adding new J1939 PID:s to FMS snif 

### ISSUE THREAD

**Issue by anterosa** [JonnoFTW/rpi-can-logger#2]
If I add new PID:s to fms_pids.py, can i use them in logging?
I have some additional standard J 1939 pid's (PGN's) needed for logging.
Additionally I am new to rpi-can-logger. How to change configuration in yaml files?
Especially meaning of log-size and log-trigger?

**Comment by JonnoFTW** [comment]
Yes, you can add your own PIDs to be logged to fms_pids.py. In order to have your logger log them you'll need to add them to the `log-pids` list in the yaml file with the same name that appears in the `_pids` list in fms_pids.py: https://github.com/JonnoFTW/rpi-can-logger/blob/master/rpi_can_logger/logger/fms_pids.py#L247-L287

 The  arguments to `FMSPID` are:

1. The PID
2. the name you add to the yaml file
3. name of the function you will need to write in order to parse the pid. The `_fms` function is useful here, see other usages
4. A friendly name or list of friendly names returned by the above function. Compare line 257 and 259

The `log-size` option in the yaml file will limit the size of individual log files to 32mb before rotating. This is mentioned in the readme file. Please read it all carefully as it details how to setup the entire process.

**Comment by anterosa** [comment]
log-trigger: PID_MAF_FLOW # when this PID is seen, return the buffer in current state (only works in sniffing mode) 
--> If I understand correctly, PID values are written to log when receiving that PID?

**Comment by JonnoFTW** [comment]
That is correct, if you read the code for the `FMSLogger` you can see that it does this:

https://github.com/JonnoFTW/rpi-can-logger/blob/07a67a3b90fd6efcb8df0a66504953446acf0b2e/rpi_can_logger/logger/loggers.py#L281-L298

Basically it will accumulate as much data as it can within 1 second and then write the values it saw to the log or if it sees that PID.

**Comment by anterosa** [comment]
Thanks! I will try to add new PID's and test. I have used my own python-can based code, but it is only writing logs to file.
 Want to test visualization and database access.
